name = "excision"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Excision"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/joelriou/mathlib4.git"
rev = "sset-relative-homology"

[[lean_lib]]
name = "Excision"
