name = "excision"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Excision"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "eb6a272ec5968ee3d5f6f02bd4232f057c25073b"

[[lean_lib]]
name = "Excision"
